### ISSUE TITLE
ERROR:root:Malformed output from ACE

### ISSUE THREAD

**Issue by johntzwei** [delph-in/pydelphin#154] opened 2018-06-26 13:50 UTC
Hi Michael,

I am trying to parse using the ACE interface, with the most recent executable on Linux and the (1214) version of the ERG.dat file provided on the ACE webpage. My code looks like:

```
response = ace.parse_from_iterable(
        grm='ace-0.9.27/erg-1214-x86-64-0.9.27.dat',                                                                 
        data=itertools.islice(isplit(handle.read()), 0, 100),
        executable='ace-0.9.27/ace',
        cmdargs=['-1', '-X', '--timeout', '7']                                                                  
    )

next(response)
```

and I am getting the error

`ERROR:root:Malformed output from ACE:
NOTE: parsed 1 / 1 sentences, avg 1048k, time 0.01633s
Exception ignored in: <generator object parse_from_iterable at 0x7fc34adc8bf8>                               Traceback (most recent call last):
File "/iesl/canvas/jwei/nmt_hpsg/erg/lib/python3.5/site-packages/delphin/interfaces/ace.py", line 409, in parse_from_iterable
File "/iesl/canvas/jwei/nmt_hpsg/erg/lib/python3.5/site-packages/delphin/interfaces/ace.py", line 160, in __exit__
File "/iesl/canvas/jwei/nmt_hpsg/erg/lib/python3.5/site-packages/delphin/interfaces/ace.py", line 271, in close
File "/home/jwei/anaconda3/lib/python3.5/subprocess.py", line 1658, in wait
File "/home/jwei/anaconda3/lib/python3.5/subprocess.py", line 1608, in _try_wait                           AttributeError: 'NoneType' object has no attribute 'waitpid'
`
I will look into see what the problem is, but if you think you know the problem let me know! Thanks!

**Comment by johntzwei** [comment] 2018-06-26 15:02
I seemed to have found the issue. For python3, the context manager for an `AceParser` closes when you use the yield method (in the `parse_from_iterable` function in the ACE interface).

I have the code for python3, and I will push it sometime today. Thanks!

**Comment by goodmami** [comment] 2018-06-26 18:09
Let's not close the issue until the bug is fixed or deemed invalid.

The following works for me, which is about the same as yours but doesn't use `isplit()` (what does that do?)

```python
>>> from delphin.interfaces import ace
>>> import itertools
>>> with open('ex.txt') as fh:
...     response = ace.parse_from_iterable(
...         grm='../../grammars/erg-1214-x86-64-0.9.27.dat',
...         data=itertools.islice(fh,0,1),
...         executable='/opt/ace-0.9.27/ace',
...         cmdargs=['-1','-X','--timeout', '7']
...     )
...     print(next(response))
... 
sentential -- stopping
ParseResponse({'NOTES': [], 'WARNINGS': [], 'ERRORS': [], 'run': {'run-id': 0, 'application': 'ACE 0.9.27 via PyDelphin v0.7.2', 'environment': '-1 -X --timeout 7 --tsdb-notes --tsdb-stdout --report-labels', 'user': 'goodmami', 'host': 'tpy', 'os': 'Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic', 'start': datetime.datetime(2018, 6, 26, 9, 45, 21, 350566), 'platform': 'gcc 4.2', 'grammar': 'ERG (1214)', 'avms': 9280, 'lexicon': 38259, 'lrules': 81, 'rules': 212}, 'input': 'Abrams chased Browne.\n', 'surface': None, 'results': [{'result-id': 0, 'derivation': '(888 sb-hd_mc_c 1.274873 0 3 (882 hdn_bnp-pn_c 0.093057 0 1 (881 n_sg_ilr 0.135806 0 1 (83 abrams 0.000000 0 1 ("abrams" 50 "token [ +FORM \\"abrams\\" +FROM \\"0\\" +TO \\"6\\" +ID *diff-list* [ LIST *list* LAST *list* ] +TNT null_tnt [ +TAGS *null* +PRBS *null* +MAIN tnt_main [ +TAG \\"NNP\\" +PRB \\"1.0\\" ] ] +CLASS alphabetic [ +INITIAL + +CASE capitalized+lower ] +TRAIT token_trait [ +UW - +IT italics +LB bracket_null +RB bracket_null +HD token_head [ +LL ctype [ -CTYPE- string ] +TG string +TI \\"0\\" ] ] +PRED predsort +CARG \\"Abrams\\" +TICK bool ]")))) (887 hd-cmp_u_c 0.519222 1 3 (883 v_pst_olr -0.551752 1 2 (64 chase_v1 0.000000 1 2 ("chased" 44 "token [ +FORM \\"chased\\" +FROM \\"7\\" +TO \\"13\\" +ID *diff-list* [ LIST *list* LAST *list* ] +TNT null_tnt [ +TAGS *null* +PRBS *null* +MAIN tnt_main [ +TAG \\"NNP\\" +PRB \\"1.0\\" ] ] +CLASS alphabetic [ +INITIAL - +CASE non_capitalized+lower ] +TRAIT token_trait [ +UW - +IT italics +LB bracket_null +RB bracket_null +HD token_head [ +LL ctype [ -CTYPE- string ] +TG string +TI \\"7\\" ] ] +PRED predsort +CARG \\"chased\\" +TICK bool ]"))) (886 hdn_bnp-pn_c 0.744621 2 3 (885 w_period_plr 0.333141 2 3 (884 n_sg_ilr -0.102185 2 3 (84 browne 0.000000 2 3 ("browne." 51 "token [ +FORM \\"browne.\\" +FROM \\"14\\" +TO \\"21\\" +ID *diff-list* [ LIST *list* LAST *list* ] +TNT null_tnt [ +TAGS *null* +PRBS *null* +MAIN tnt_main [ +TAG \\"NNP\\" +PRB \\"1.0\\" ] ] +CLASS alphabetic [ +INITIAL - +CASE capitalized+lower ] +TRAIT token_trait [ +UW - +IT italics +LB bracket_null +RB bracket_null +HD token_head [ +LL ctype [ -CTYPE- string ] +TG string +TI \\"14\\" ] ] +PRED predsort +CARG \\"Browne\\" +TICK bool ]")))))))', 'mrs': '[ LTOP: h0 INDEX: e2 [ e SF: prop TENSE: past MOOD: indicative PROG: - PERF: - ] RELS: < [ proper_q<0:6> LBL: h4 ARG0: x3 [ x PERS: 3 NUM: sg IND: + ] RSTR: h5 BODY: h6 ]  [ named<0:6> LBL: h7 CARG: "Abrams" ARG0: x3 ]  [ _chase_v_1<7:13> LBL: h1 ARG0: e2 ARG1: x3 ARG2: x9 [ x PERS: 3 NUM: sg IND: + ] ]  [ proper_q<14:21> LBL: h10 ARG0: x9 RSTR: h11 BODY: h12 ]  [ named<14:21> LBL: h13 CARG: "Browne" ARG0: x9 ] > HCONS: < h0 qeq h1 h5 qeq h7 h11 qeq h13 > ]', 'tree': '("S" ("NP" ("N" ("N" ("abrams")))) ("VP" ("V" ("V" ("chased"))) ("NP" ("N" ("N" ("N" ("browne.")))))))', 'flags': [(':ascore', 1.274873), (':probability', 1.0)]}], 'ninputs': 4, 'tokens': {'initial': '(1, 0, 1, <0:6>, 1, "Abrams", 0, "null", "NNP" 1.0) (2, 1, 2, <7:13>, 1, "chased", 0, "null", "NNP" 1.0) (3, 2, 3, <14:20>, 1, "Browne", 0, "null", "NNP" 1.0) (4, 3, 4, <20:21>, 1, ".", 0, "null", "." 1.0)', 'internal': '(40, 2, 3, <14:21>, 1, "Browne.", 0, "null") (44, 1, 2, <7:13>, 1, "chased", 0, "null") (47, 0, 1, <0:6>, 1, "Abrams", 0, "null") (48, 1, 2, <7:13>, 1, "chased", 0, "null") (49, 2, 3, <14:21>, 1, "Browne.", 0, "null") (50, 0, 1, <0:6>, 1, "abrams", 0, "null") (51, 2, 3, <14:21>, 1, "browne.", 0, "null") (53, 1, 2, <7:13>, 1, "chased", 0, "null") (54, 0, 1, <0:6>, 1, "abrams", 0, "null") (55, 2, 3, <14:21>, 1, "browne.", 0, "null")'}, 'copies': 263, 'unifications': 31626, 'ntokens': 10, 'readings': 1, 'pedges': 48, 'aedges': 106, 'total': 51, 'treal': 124, 'tcpu': 51, 'others': 2121652})
```

Note: the `sentential -- stopping` line is on STDERR.

Some things about your example, though:

* Why bother with the `islice()`? When you open a file handle, reading from the file is already iterative. In fact, when you do `handle.read()`, you are loading the full contents of the file into memory, which negates any (redundant) benefits of creating a Python-generator over it. You might as well just do `handle.readlines()[:100]`
* Does `isplit()` split lines or tokens? ACE expects full lines (sentences) as input, generally.
* Why do you use the `-X` option, which ACE itself [does not recommend](http://moin.delph-in.net/AceOptions)? I think using `-X` negates the effect of `-1`. The former returns the *first* result that ACE finds, while the latter returns the *top* result based on the parse ranking model. I don't know which is returned if you use both (probably the first, not (necessarily) the top).

I think a simpler calling of `parse_from_iterable()` would be less prone to errors:

```python
>>> from delphin.interfaces import ace
>>> with open('ex.txt') as fh:
...     for response in ace.parse_from_iterable(
...             '../../grammars/erg-1214-x86-64-0.9.27.dat',
...             fh,
...             executable='/opt/ace-0.9.27/ace',
...             cmdargs=['-1','--timeout', '7']):
...         # do something with response
```

Also, while looking into this problem, I uncovered a bug when a blank line is sent to ACE. See #155.

**Comment by goodmami** [comment] 2018-06-26 18:10
Also...

> For python3, the context manager for an `AceParser` closes when you use the yield method (in the `parse_from_iterable` function in the ACE interface).

I don't believe that is true. It could be that some input passed to ACE caused a crash which closed the process, but it's supposed to recover from those situations. Can you provide an input example that causes the problem you're experiencing?

**Comment by goodmami** [comment] 2018-06-30 15:40
@johntzwei Can you provide a minimal working example that causes the error to occur? Specifically, I need to know what `isplit()` does and an example sentence or two that you're using.

**Comment by goodmami** [comment] 2018-07-06 07:01
@johntzwei Looking a little closer at your error message, it is actually quite odd, expecially this part:

> File "/home/jwei/anaconda3/lib/python3.5/subprocess.py", line 1608, in _try_wait AttributeError: 'NoneType' object has no attribute 'waitpid'

The `_try_wait()` method in Python 3.5 looks like this:

```python
    def _try_wait(self, wait_flags):
        """All callers to this function MUST hold self._waitpid_lock."""
        try:
            (pid, sts) = os.waitpid(self.pid, wait_flags)
        except ChildProcessError:
            # This happens if SIGCLD is set to be ignored or waiting
            # for child processes has otherwise been disabled for our
            # process.  This child is dead, we can't get the status.
            pid = self.pid
            sts = 0
        return (pid, sts)
```

That error would be thrown if the `os` symbol were `None`. The top of the file has `import os`, so something later did something like `subprocess.os = None`. I don't use Anaconda, so it's possible that it did something strange, but I'm not sure what setting `os` to `None` would accomplish. Or perhaps your code reset the `os` symbol on accident?

Anyway, I think I will close this issue soon if the error cannot be reproduced.

**Comment by goodmami** [comment] 2018-07-25 22:19
The error could not be reproduced so I'm closing this as invalid.

**Closed by goodmami** 2018-07-25 22:19 UTC
