### ISSUE TITLE
missing import for REPP

### ISSUE THREAD

**Issue by odanoburu** [delph-in/pydelphin#223] opened 2019-05-30 14:20 UTC
I installed `pydelphin` from a virtualenv in Fedora 29. I tried using the REPP tokenizer form the CLI and got an error that seems to be caused by a missing import:
```
(venv) $ delphin repp -c ~/work/hpsg/erg/pet/repp.set --format triple <<< "hello my friend."                                                 
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 5
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 3
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 11
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 15
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 2
  self._re = re.compile(pattern)
Traceback (most recent call last):
  File "/home/odanoburu/work/sensetion/repsense/venv/bin/delphin", line 10, in <module>
    sys.exit(main())
  File "/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/main.py", line 35, in main
    args.func(args)
  File "/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/main.py", line 117, in call_repp
    trace_level=(args.trace and args.verbosity) or 0)
  File "/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/commands.py", line 583, in repp
    _repp(r, line, format, trace_level)
  File "/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/commands.py", line 611, in _repp
    if t.lnk.type == Lnk.CHARSPAN:
NameError: name 'Lnk' is not defined
```

adding the import seems to have fixed the problem:
```
(venv)$ delphin repp -c ~/work/hpsg/erg/pet/repp.set --format triple <<< "hello my friend."
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 5
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 3
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 11
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 15
  self._re = re.compile(pattern)
/home/odanoburu/work/sensetion/repsense/venv/lib/python3.7/site-packages/delphin/repp.py:119: FutureWarning: Possible nested set at position 2
  self._re = re.compile(pattern)
(0, 5, hello)
(6, 8, my)
(9, 15, friend)
(15, 16, .)
```

**Comment by goodmami** [comment] 2019-05-30 15:08
I have confirmed the issue on a fresh install. There is, as you say, a missing import in `delphin/commands.py`.

This has already been fixed in the [v1.0.0](https://github.com/delph-in/pydelphin/tree/v1.0.0) branch and will be included in the v1.0.0 release, so I'm not inclined to make a v0.9.3 release for it.

The FutureWarnings also surprised me, but there's nothing PyDelphin can do about them (besides ignore them). Python 3.7 warns about `[` at the start of a character set (e.g., `[[a]` is the character set of `[` and `a` characters) because Python is preparing to expand its regex features and these conflict with the syntax (see [here](https://bugs.python.org/issue30349)). These patterns are defined in the ERG's REPP files, so the ERG would need to be modified just to prevent some Python warnings, and I don't foresee that happening.

Thanks for reporting the bug!

**Closed** 2019-06-03 15:20 UTC
