### ISSUE TITLE
Reading derivations from raw tsdb result files doesn't work due to double backslashes

### ISSUE THREAD

**Issue by johntzwei** [delph-in/pydelphin#151] opened 2018-06-19 04:36 UTC
Hi Michael!

I was trying to read in derivations directly from the raw tsdb result files because the `delphin.itsdb` module was too slow (perhaps worthy of an issue within itself?) and I found out that those derivations will not load with `delphin.derivation.Derivation` because they are double backslash escaped, where as the module expects single backslash escaped.

I hope this is helpful. Thanks for all your work!

**Comment by goodmami** [comment] 2018-06-19 05:43
Hi, can you provide some more information, possibly with a snippet of code? Some questions:

- what version of PyDelphin are you using? (`from delphin.__about__ import __version__`)
- how are you using `delphin.itsdb`?
- What data/grammar are you using?
- What processor produced the profiles? (ACE, LKB, web API, etc)

I know that the web API run at the University of Oslo double-backslash-escapes its derivations, but maybe that problem occurs in other UiO software as well. But in general I don't have a problem loading derivations from profiles:

```python
>>> from delphin import itsdb, derivation
>>> ts = itsdb.TestSuite('../../grammars/erg/tsdb/gold/mrs')
>>> d = derivation.Derivation.from_string(ts['result'][0]['derivation'])
>>> d.terminals()
[<UdfTerminal object (it) at 140597977032008>, <UdfTerminal object (rained.) at 140597977032648>]
```

Feel free to open a separate issue for `delphin.itsdb` performance. That module has undergone some significant changes recently and I haven't profiled its performance yet.

**Comment by johntzwei** [comment] 2018-06-19 14:34
I recently made a parse of 200,000 sentences with the `logon/parse` script (ERG) which wrote a tsdb database to `logon/lingo/lkb/src/tsdb/home/erg/1214/results.proc/18-06-14/pet`. Because the `delphin.itsdb` wouldn't load the profile, I read the `result` file through an io stream.

The version of pydelphin is 0.7.0, which I installed with pip. Hope this helps!

**Comment by goodmami** [comment] 2018-06-19 17:10
Thanks for the info. And sorry I misunderstood that you're not using the `itsdb` module. A few things:

- Creating a profile of 200,000 items is probably not a good idea. It would be best to break it up, e.g., into 200 profiles of 1000 items each. Currently, `delphin.itsdb` loads the entire profile in memory (a bit of a regression; see the third item in #150), and PyDelphin's data structures for holding profiles takes up ~2x the size of the profile on disk, so such a large profile could easily use up all your memory. Perhaps this is why it didn't work for you?

- If you're reading the `result` file without using any functions from `delphin.itsdb`, be aware that 3 things are always escaped in [incr tsdb()] files: `@`, newlines, and backslashes. Thus, the double-backslash you're seeing is just an escaped single backslash. If you want to (or have to) process the `result` file manually, I suggest either:
  - using [`delphin.itsdb.unescape()`](https://github.com/delph-in/pydelphin/wiki/delphin.itsdb#unescape) on the derivation string you extracted
  - using [`delphin.itsdb.decode_row()`](https://github.com/delph-in/pydelphin/wiki/delphin.itsdb#decode_row) on the entire line. For your purposes, the `fields` parameter is not necessary.
Either of these should resolve your issue and won't take up excess memory.

  (BTW, I'm currently improving the documentation, but I don't have updated links yet. Sorry if those wiki links aren't easy to read.)

- PyDelphin v0.7.0 should be fine. If you're using Python 2.7 I would suggest updating to v0.7.1 or v0.7.2, but otherwise I don't think there's a big difference.

**Comment by goodmami** [comment] 2018-06-20 18:08
@johntzwei, when you get a chance, can you confirm if my previous suggestion resolved your issue?

And is there some change you're hoping to see in PyDelphin? (perhaps the ability to process very large profiles).

**Comment by johntzwei** [comment] 2018-06-21 05:29
Thank you for your suggestions! I was also the one who asked for help on unknown word handling in ERG, so you have helped me twice. Thanks! What I have done is basically used a `str.replace('\\\\','\\')` as a quick way to read in the derivations, and it seems to work fine. I had not realized there were unescape functions.

For changes, I think things like the ACE interface are really nice. I'm not sure if other developers would approve, but having a python interface for the PET with good documentation for all the options and saving that bypasses itsdb and uses something more modern like mysql/mongodb would be really nice.

**Comment by goodmami** [comment] 2018-06-21 05:59
Ah, sorry, I didn't make that connection. I hope you were able to resolve the unknown word handling issue, too.

I think your solution does the same thing as `unescape()` for backslashes, but it would miss any escaped `@` characters (`\s`) or newlines (`\n`). Otherwise it should be sufficient.

Regarding changes... hmm, you can create a new issue for a PET interface, but I'm not sure I have time to implement it. PET has a lot of options, and I don't (yet) know how to parse its stdout, but it should be possible. And I actually had implemented a Pandas backend for [incr tsdb()] profiles, but removed it (for now) because it, being a compiled module, made the dependencies a bit more complicated. It would be nice to provide a `to_dataframe()` method on Tables, perhaps. I agree that it would be nice to allow modern tools to more easily query our data.

BTW, I'll be updating PyDelphins documentation soon. I hope you find it useful.

**Comment by goodmami** [comment] 2018-06-22 05:52
@johntzwei oops, I mentioned the new documentation twice but gave no links. It's now up, but I haven't officially linked to it yet. You can find it here: http://pydelphin.readthedocs.io/; or more specifically, this one: http://pydelphin.readthedocs.io/en/latest/api/delphin.itsdb.html#delphin.itsdb.unescape

Let me know if they can be improved more (maybe more examples?)

And I'll close this issue now. Thanks for the discussion!

**Closed by goodmami** 2018-06-22 05:52 UTC
