### ISSUE TITLE
DMRS links pointing to quantifiers rather than head nouns

### ISSUE THREAD

**Issue by guyemerson** [delph-in/pydelphin#48] opened 2016-02-01 17:37 UTC
In DMRS, predicates are collapsed with their ARG0 variables as a single node.  Whenever another predicate takes that variable as an argument, there should be a DMRS link to that node.  However, when loading from simplemrs and dumping to dmrx, the link may point to the quantifier node instead.

Minimal example:

`>>> mrs = delphin.mrs.simplemrs.loads_one('[ RELS: < [ _the_q LBL: h3 ARG0: x1 RSTR: h2 ] [ _dog_n_1 LBL: h1 ARG0: x1 ] [ _bark_v_1 LBL: h4 ARG0: e1 ARG1: x1 ] > HCONS: < h2 qeq h1 > ]')`
`>>> delphin.mrs.dmrx.dumps_one(mrs)`
`'<dmrs-list><dmrs cfrom="-1" cto="-1"><node cfrom="-1" cto="-1" nodeid="10000"><realpred lemma="_the_q" /><sortinfo cvarsort="x" /></node><node cfrom="-1" cto="-1" nodeid="10001"><realpred lemma="_dog_n_1" /><sortinfo cvarsort="x" /></node><node cfrom="-1" cto="-1" nodeid="10002"><realpred lemma="_bark_v_1" /><sortinfo cvarsort="e" /></node><link from="10000" to="10001"><rargname>RSTR</rargname><post>H</post></link><link from="10002" to="10000"><rargname>ARG1</rargname><post>NEQ</post></link></dmrs></dmrs-list>'`

The last link is from 10002 to 10000, but it should be to 10001 instead.

**Comment by guyemerson** [comment] 2016-02-01 17:45
I haven't been able to reproduce this bug when instantiating the MRS directly as an Xmrs object:

`>>> theEP = delphin.mrs.ElementaryPredication(nodeid=10000, pred=pPred.stringpred('_the_q_rel'), label='h3', args={'RSTR':'h2', 'ARG0':'x1'})`
`>>> dogEP = delphin.mrs.ElementaryPredication(nodeid=10001, pred=pPred.stringpred('_dog_n_1_rel'), label='h1', args={'ARG0':'x1'})`
`>>> barkEP = delphin.mrs.ElementaryPredication(nodeid=10002, pred=pPred.stringpred('_bark_v_1_rel'), label='h4', args={'ARG0':'e1', 'ARG1':'x1'})`
`>>> hcon = delphin.mrs.HandleConstraint('h2', 'qeq', 'h1')`
`>>> mrs = delphin.mrs.Mrs(rels=[theEP, dogEP, barkEP], hcons=[hcon])`
`>>> delphin.mrs.dmrx.dumps_one(mrs)`
`'<dmrs-list><dmrs cfrom="-1" cto="-1"><node cfrom="-1" cto="-1" nodeid="10000"><realpred lemma="the" pos="q" /><sortinfo /></node><node cfrom="-1" cto="-1" nodeid="10001"><realpred lemma="dog" pos="n" sense="1" /><sortinfo cvarsort="x" /></node><node cfrom="-1" cto="-1" nodeid="10002"><realpred lemma="bark" pos="v" sense="1" /><sortinfo cvarsort="e" /></node><link from="10000" to="10001"><rargname>RSTR</rargname><post>H</post></link><link from="10002" to="10001"><rargname>ARG1</rargname><post>NEQ</post></link></dmrs></dmrs-list>'`

The final link is correct.

**Comment by guyemerson** [comment] 2016-02-01 17:58
Okay, if you add `_rel` to the predicate names in the first example, it works. I guess the quantifiers are not being recognised correctly without that.

For some reason, under http://svn.emmtee.net/erg/trunk/tsdb/gold, the predicate names have the `_rel` suffix, but under http://svn.emmtee.net/erg/tags/1214/tsdb/gold, they don't.

**Comment by goodmami** [comment] 2016-02-03 00:25
Thanks, @guyemerson . I haven't poked the issue yet myself, but your conclusions seem reasonable. I'm currently detecting if something is a quantifier by looking at the predicate's POS value, and a predicate like `the_q` doesn't look like what I expect, so I fail to set `q` as the POS. This is part of two larger problems: the [valid forms of predicates](http://lists.delph-in.net/archives/developers/2016/002189.html) and [how to detect quantifiers](http://lists.delph-in.net/archives/developers/2016/002174.html).

**Comment by guyemerson** [comment] 2016-02-03 09:06
I can see that fixing either of those problems (i.e. accepting _rel-less preds, or detecting quantifiers with RSTR) would fix this issue.

Either way, I think it might make sense to check for DMRS compatibility before doing the conversion - for any variable, there should be a unique predicate taking it as ARG0 (except for quantifiers).  Throwing an error (or at least a warning) if this is not the case would be a very helpful indication that something's going wrong.

**Comment by goodmami** [comment] 2016-02-03 19:54
Indeed. I should make one or both of those fixes and push a new version of pyDelphin. I haven't given this repo much attention for the last few months.

> Either way, I think it might make sense to check for DMRS compatibility before doing the conversion

Yes, but a full check would make things rather slow; and could be annoying if you are running a batch process to convert many MRSs and pyDelphin quits in the middle of it. Instead, users who care about the cleanliness of their representations can manually check an Xmrs with [`Xmrs.is_well_formed()`](https://github.com/delph-in/pydelphin/blob/7a2136f303ac3a51b01b88645e9ee42bd58970eb/delphin/mrs/xmrs.py#L476) (assuming that a well-formed Xmrs is compatible with DMRS)

> for any variable, there should be a unique predicate taking it as ARG0 (except for quantifiers). 

I would say "for any `x` or `e` variable" since `i`, `p`, `u`, and `h` variables don't need to be or can't be ARG0s. But there's some disagreement about whether we can have an `x` or `e` without the predication for which it is an ARG0, and I've also seen `i` variables (and maybe even `u`) as ARG0s for some predications. Where my intuitive understanding of *MRS was at odds with *MRSs I observed in the wild, I opted for pyDelphin to be more robust and attempt to model (what I thought was) ill-formed *MRSs.

> Throwing an error (or at least a warning) if this is not the case would be a very helpful indication that something's going wrong.

In some cases I do throw errors ([example](https://github.com/delph-in/pydelphin/blob/7a2136f303ac3a51b01b88645e9ee42bd58970eb/delphin/mrs/xmrs.py#L108)), and at one point I threw warnings or log messages, but yes, I should be more consistent about this. The rule of thumb is: raise an exception if the problem is unrecoverable, warn if it might give unexpected results but can otherwise safely be ignored, and be quiet for things that are simply surprising but don't cause problems.

Thanks!

**Comment by guyemerson** [comment] 2016-02-04 08:51
I see.  Then maybe a more robust check would be: if two preds have the same ARG0, one of them must be a quantifier; more than two preds are not allowed.

**Comment by goodmami** [comment] 2016-02-08 23:29
Perhaps, but that, too, has been violated in MRS (in Jacy). It's not compatible with DMRS, so a warning during DMRS conversion could be useful, as you say.

I fixed the quantifier-detection thing (both by looking for RSTR in the args of an EP and by making Pred parsing a bit more robust to missing _rel suffixes), so I'm resolving this issue when the changes get merged to master.

**Comment by fcbond** [comment] 2016-02-09 05:44
G'day,

> Perhaps, but that, too, has been violated in MRS (in Jacy). It's not compatible with DMRS, so a warning during DMRS conversion could be useful, as you say.

These are considered bugs in Jacy, and we would not object to them
MRSs being rejected, not just warned.

> I fixed the quantifier-detection thing (both by looking for RSTR in the args of an EP and by making Pred parsing a bit more robust to missing _rel suffixes), so I'm resolving this issue when the changes get merged to master.
>
> —
> Reply to this email directly or view it on GitHub.




-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by goodmami** [comment] 2016-02-09 17:57
@fcbond: maybe something configurable? Something like:

```python
simplemrs.load_one('nonconformant.mrs', robust=True)
```

Or instead of `robust=True|False`, have something like `errors='ignore'|'warn'|'strict'` (analogous to Python's [str.encode()](https://docs.python.org/3/library/stdtypes.html#str.encode))

**Comment by fcbond** [comment] 2016-02-10 03:30
The second approach looks good.

On Wed, Feb 10, 2016 at 1:57 AM, Michael Wayne Goodman <
notifications@github.com> wrote:

> @fcbond <https://github.com/fcbond>: maybe something configurable?
> Something like:
>
> simplemrs.load_one('nonconformant.mrs', robust=True)
>
> Or instead of robust=True|False, have something like
> errors='ignore'|'warn'|'strict' (analogous to Python's str.encode()
> <https://docs.python.org/3/library/stdtypes.html#str.encode>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/delph-in/pydelphin/issues/48#issuecomment-181981833>.
>



-- 
Francis Bond <http://www3.ntu.edu.sg/home/fcbond/>
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Closed** 2016-03-03 20:09 UTC
Labels: fixcommitted
